export enum PermissionEnum {
  USER_VIEW="USER_VIEW",
  USER_CREATE="USER_CREATE",
  USER_UPDATE="USER_UPDATE",
  USER_DELETE="USER_DELETE",
  CREATE_CATEGORY="CREATE_CATEGORY",
  DELETE_CATEGORY="DELETE_CATEGORY",
  UPDATE_CATEGORY="DELETE_CATEGORY",
}
